# Generated by Django 2.2.2 on 2020-02-19 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instaclone', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_picture', models.ImageField(default='logo.jpg', upload_to='profile_pictures')),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('uploads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='instaclone.Upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Users' Profile",
            },
        ),
    ]
